sudo: required
services:
    - docker

before_install:
    - docker build -t flytaly/docker-react-tests -f Dockerfile.dev .

script:
    - docker run flytaly/docker-react-tests npm run test -- --coverage
